# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb3ab6cc5033eb080d36eebf7f099e531e4364cd0740ea956344a8519c016decea6440cc8052bb00fad7d4ce73c800866daa6271a1805ef531f96f357fc1e1b1

test:
  secret_key_base: 52d0bc3af931ebef05866ae6e31f6907d83a95980c10e91f0bb3922ad4a6ebbed053f9bf49c8b630db5d126577da30173cfeedb534f67544eb8619f4199264fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
